fix(1191): updating to correct version during deployment of example apps

diff --git a/.github/workflows/shipit_pr_and_example_apps_deployment.yml b/.github/workflows/shipit_pr_and_example_apps_deployment.yml
--- a/.github/workflows/shipit_pr_and_example_apps_deployment.yml
+++ b/.github/workflows/shipit_pr_and_example_apps_deployment.yml
@@ -89,9 +89,6 @@ jobs:
           cd ../components-react
           jq --arg CANARY_VERSION "$CANARY_VERSION" '.dependencies["@infineon/infineon-design-system-stencil"] = $CANARY_VERSION' package.json > package.json.tmp && mv package.json.tmp package.json          
           npm install
-          UPDATED_VERSION=$(jq -r '.dependencies["@infineon/infineon-design-system-stencil"]' package.json)
-          echo "Version update in package.json from: $CANARY_VERSION to: $UPDATED_VERSION"
-    
           cd ../../
           git config user.name "github-actions"
           git config user.email "github-actions@github.com"
@@ -183,6 +180,18 @@ jobs:
           echo "Verifying the installed version of the Stencil library"
           npm list @infineon/infineon-design-system-stencil
           npm list @infineon/infineon-design-system-react
+          UPDATED_VERSION=$(jq -r '.dependencies["@infineon/infineon-design-system-stencil"]' package.json)
+          if [ "$UPDATED_VERSION" != "${{ needs.stencil-library-release.outputs.CANARY_VERSION }}" ]; then
+            echo "Version update failed in package.json"
+            exit 1
+          fi
+          echo "Version update in package.json successful: $UPDATED_VERSION"
+          INSTALLED_VERSION=$(npm list @infineon/infineon-design-system-stencil --depth=0 | grep @infineon/infineon-design-system-stencil@ | awk -F@ '{print $3}')
+          if [ "$INSTALLED_VERSION" != "${{ needs.stencil-library-release.outputs.CANARY_VERSION }}" ]; then
+            echo "Installed version mismatch: expected ${{ needs.stencil-library-release.outputs.CANARY_VERSION }} but got $INSTALLED_VERSION"
+            exit 1
+          fi
+          echo "Installed version verified: $INSTALLED_VERSION"
           npm run build
 
       - name: Deploy preview
